---
kind: pipeline
name: build

steps:
  - name: deps
    image: golang:1.14.4-buster
    volumes:
      - name: deps
        path: /go
    environment:
      GOPROXY: https://proxy.golang.org
    commands:
      - make deps

  - name: gosec
    image: golang:1.14.4-buster
    volumes:
      - name: deps
        path: /go
    environment:
      GOPROXY: https://proxy.golang.org
    commands:
      - make gosec
    depends_on:
      - deps

  - name: golangci-lint
    image: golang:1.14.4-buster
    volumes:
      - name: deps
        path: /go
    environment:
      GOPROXY: https://proxy.golang.org
    commands:
      - make golangci-lint
    depends_on:
      - deps

  - name: opa-tests
    image: node:12.12.0-buster
    commands:
      - wget --quiet https://github.com/open-policy-agent/opa/releases/download/v0.22.0/opa_linux_amd64 -O /usr/local/bin/opa
      - chmod +x /usr/local/bin/opa
      - make opa-tests
    depends_on:
      - gosec
      - golangci-lint

  - name: go-test
    image: golang:1.14.4-buster
    volumes:
      - name: deps
        path: /go
    environment:
      GOPROXY: https://proxy.golang.org
    commands:
      - make test
    depends_on:
      - gosec
      - golangci-lint


volumes:
  - name: deps
    temp: {}

---
kind: pipeline
name: release

depends_on:
  - build

trigger:
  event:
    - tag

steps:
  - name: container-image
    image: plugins/docker
    settings:
      registry:
        from_secret: registry
      username:
        from_secret: registry_user
      password:
        from_secret: registry_password
      repo: quay.io/sighup/opa-notary-connector
      dockerfile: build/Dockerfile
      purge: true
      force_tag: true
      auto_tag: true
      build_args:
        - VERSION=${DRONE_TAG}
        - COMMIT=${DRONE_COMMIT}

  - name: github-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      title: Release ${DRONE_TAG}
      note: docs/releases/${DRONE_TAG}.md
      overwrite: true
      files:
        - LICENSE
