kind: pipeline
name: release

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
    when:
      event: 
        - tag

  - name: test
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go test -race -v ./... -cover

  - name: release
    image: docker.io/library/golang:1.14.4-buster
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      REGISTRY:
        from_secret: registry
      REGISTRY_USER:
        from_secret: registry_user
      REGISTRY_PASSWORD:
        from_secret: registry_password
    volumes:
      - name: deps
        path: /go
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - curl -L https://get.docker.com | bash
      - docker login -p $${REGISTRY_PASSWORD} -u $${REGISTRY_USER} $${REGISTRY}
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: 
        - tag

volumes:
  - name: deps
    temp: {}
  - name: dockersock
    host:
      path: /var/run/docker.sock