---
project_name: opa-notary-connector
builds:
  - binary: 'opa-notary-connector'
    goarch:
      - amd64
    goos:
      - linux
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/sighupio/opa-notary-connector/cmd.version={{.Version}} -X github.com/sighupio/opa-notary-connector/cmd.commit={{.Commit}} -X github.com/sighupio/opa-notary-connector/cmd.date={{.Date}}
checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
  algorithm: sha256
archives:
  - name_template: "{{ .ProjectName }}"
    format: binary
dockers:
  - image_templates:
      - quay.io/sighup/{{ .ProjectName }}:latest
      - quay.io/sighup/{{ .ProjectName }}:{{ .Tag }}
      - quay.io/sighup/{{ .ProjectName }}:v{{ .Major }}
    dockerfile: build/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
release:
  prerelease: auto
  github:
    owner: sighupio
    name: opa-notary-connector
  name_template: "{{.ProjectName}} v{{.Version}}"
