---
apiVersion: v1
kind: Secret
metadata:
  name: opa-notary-connector-config
stringData:
  trust.yaml: |
    repositories:
{{ toYaml .Values.repositories | indent 6 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-notary-connector-mode
  labels:
    openpolicyagent.org/data: opa
data:
  mode.json: '{"strict": {{ .Values.strict }}}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-notary-connector-rules
  labels:
    openpolicyagent.org/policy: rego
data:
{{ (tpl (.Files.Glob "opa-config/config.rego").AsConfig . ) | indent 2 }}
{{ (tpl (.Files.Glob "opa-config/strict.rego").AsConfig . ) | indent 2 }}
