---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: registry-root
  namespace: notary
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: registry-root-ca
  namespace: notary
spec:
  # name of the tls secret to store
  # the generated certificate/key pair
  secretName: registry-root-ca
  isCA: true
  issuerRef:
    # issuer created in step 1
    name: registry-root
    kind: Issuer
  commonName: "registry"
  dnsNames:
  # one or more fully-qualified domain name
  # can be defined here
    - registry
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: registry-root-ca
  namespace: notary
spec:
  ca:
    secretName: registry-root-ca
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: registry
  namespace: notary
spec:
  # Secret names are always required.
  secretName: registry-crt
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
  - notary
  commonName: registry
  isCA: false
  keySize: 521
  keyAlgorithm: ecdsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
  dnsNames:
    - localhost
    - registry
    - registry.notary
    - registry.notary.svc
    - registry.notary.svc.cluster.local
  issuerRef:
    name: registry-root-ca
    kind: Issuer
