# OPA Notary Connector configuration
repositories:
- name: "localhost.*"
  priority: 10
  trust:
    enabled: true
    trustServer: "https://notary-server.notary.svc.cluster.local:4443"
    signers:
    - role: "targets/jenkins"
      publicKey: "" # base64 encoded public key. Passed in Makefile local-deploy target
# OPA helm chart configuration
opa:
  logLevel: debug
